# Site settings
title: SMART CONCRETE MATURITY DEVICE
email: mtpsilva@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: AeonlabsS
github_username: aeonSolutions

# Build settings
markdown: kramdown
